### ISSUE TITLE
Chore: Update loadash package dependency for security risk.

### ISSUE THREAD

**Issue by CherryCoder91** [richie5um/FlattenJS#7]
"lodash": "4.17.20" has a known security risk which is fixed in a later minor release "lodash": "^4.17.21". 

Suggestion: 
Increment package for lodash by a minor version to "lodash": "^4.17.21". 

Workaround:
Consuming apps must specify a greater lodash version to force dependency increment despite not being a direct dependency.

**Comment by richie5um** [comment]
Sorry for the delay on this one - github's securitybot had raised it a while ago. Just updated and published to npm. Hopefully it'll show up there shortly (FlattenJS v2.1.3)
